image:  Visual Studio 2015

init:
  - git config --global core.autocrlf input

clone_folder:   c:\projects\wconsole
shallow_clone:  true

matrix:
  fast_finish:  false

platform:
  - x64
  - x86

configuration:
  - Debug
  - Release

environment:
  matrix:
    - TOOLCHAIN:  msvc10
    - TOOLCHAIN:  msvc12
    - TOOLCHAIN:  msvc14

build_script:
  - mkdir build
  - cd build
  - cmake .. %CMAKE_CONFIGURE_FLAGS%
  - cmake --build . %CMAKE_BUILD_FLAGS%

#test_script:
#  - ctest -C %CONFIGURATION% --output-on-failure
